# Generated by Django 6.0.6 on 2026-06-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_movie_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='booked_seats',
            field=models.TextField(blank=True, default=''),
        ),
    ]
