# Generated by Django 6.0.6 on 2026-06-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_numbers',
            field=models.TextField(blank=True, default=''),
        ),
    ]
