# Generated by Django 6.0.6 on 2026-06-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_booking_seat_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
